mysql:

  host: 127.0.0.1
  port: 3306
  user: root
  password: 123456
  database: ixfan
redis:
  host: "127.0.0.1"
  port: "6379"
  password: "123456"
  db: ""
cache:
  default: redis
oss:
  accessKeyId:
  accessKeySecret:
  endPoint: "http://oss-cn-shenzhen.aliyuncs.com"
  bucket: "kql-cn"